%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "Rectified"

Stereo.b: 0.0499585
# Left Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 382.391845703125
Camera1.fy: 382.391845703125
Camera1.cx: 320.8565673828125
Camera1.cy: 239.66635131835938

# Kannala-Brandt distortion parameters
Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.k3: 0.0
Camera1.k4: 0.0

# Right Camera calibration and distortion parameters (OpenCV)
Camera2.fx: 382.391845703125
Camera2.fy: 382.391845703125
Camera2.cx: 320.8565673828125
Camera2.cy: 239.66635131835938

# Kannala-Brandt distortion parameters
Camera2.k1: 0.0
Camera2.k2: 0.0
Camera2.k3: 0.0
Camera2.k4: 0.0
    
# Transformation matrix from right camera to left camera
# Stereo.T_c1_c2: !!opencv-matrix
#   rows: 4
#   cols: 4
#   dt: f
#   data: [1.0, 0.0, 0.0, 0,
#           0.0, 1.0, 0.0, 0,
#           0.0, 0.0, 1.0, 0,
#           0.0, 0.0, 0.0, 1.0]

# Lapping area between images
Camera1.overlappingBegin: 0
Camera1.overlappingEnd: 511

Camera2.overlappingBegin: 0
Camera2.overlappingEnd: 511

# Camera resolution
Camera.width: 640
Camera.height: 480

# Camera frames per second 
Camera.fps: 30

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 40.0

# Transformation from body-frame (imu) to left camera
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [1.0, 0.0, 0.0, -0.005,
          0.0, 1.0, 0.0, -0.005,
          0.0, 0.0, 1.0, 0.0117,
          0.0, 0.0, 0.0, 1.0]

# IMU noise (Use those from VINS-mono)
# IMU.NoiseGyro: 0.00016 # 0.004 (VINS) # 0.00016 (TUM) # 0.00016    # rad/s^0.5 
# IMU.NoiseAcc: 0.0028 # 0.04 (VINS) # 0.0028 (TUM) # 0.0028     # m/s^1.5
# IMU.GyroWalk: 0.000022 # 0.000022 (VINS and TUM) rad/s^1.5
# IMU.AccWalk: 0.00086 # 0.0004 (VINS) # 0.00086 # 0.00086    # m/s^2.5
# IMU.Frequency: 200.0

IMU.NoiseGyro: 1e-3 # 2.44e-4 #1e-3 # rad/s^0.5
IMU.NoiseAcc: 1e-2 # 1.47e-3 #1e-2 # m/s^1.5
IMU.GyroWalk: 1e-6 # rad/s^1.5
IMU.AccWalk: 1e-4 # m/s^2.5
IMU.Frequency: 200.0
#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000 # Tested with 1250

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0
